### ISSUE TITLE
Does not work with SvelteKit SSR

### ISSUE THREAD

**Issue by Sparkier** [vega/svelte-vega#977]
`vega-embed` depends on `json-stringily-pretty-compact`, but that does not work when SSR is enabled:

```
SyntaxError: Cannot use import statement outside a module
```

Disabling SSR via `export const ssr = false;` will fix things, but that is certainly not ideal.

**Comment by domoritz** [comment]
Looks like we only use it for the "view source" in https://github.com/vega/vega-embed/blob/2dfdf591c86462077fc780dd717d40681ffed6aa/src/embed.ts#L4. It's a super simple library: https://github.com/lydell/json-stringify-pretty-compact/blob/main/index.js. Maybe if we update to v4, this issue goes away since that's esm?

**Comment by Sparkier** [comment]
Could very well be. Are you planning to update vega-embed to v4? If so, I can test.

**Comment by domoritz** [comment]
Done. Try 6.29.0.

**Comment by Sparkier** [comment]
Still getting:
![Image](https://github.com/user-attachments/assets/abe7ae7a-7d96-4f7f-bf3a-51db35b7b780)

Not much more time to explore further today. Can look into it again later this week.

**Comment by domoritz** [comment]
Thanks for trying and thanks for pushing me to finally update this dependency across our stack.

**Comment by Sparkier** [comment]
I saw this might be fixed with a move to esm for all packages. Are you planning to cut releases soon for the updated packages? I keep running into this issue with different projects from time to time and was wondering if I should investigate or if there is a solution on the horizon.

**Comment by domoritz** [comment]
I'm working through it. Just need to do Vega now. I'm going on vacation next week but still try to get it done by pie day.

**Comment by Sparkier** [comment]
Awesome to hear, enjoy the time off!

**Comment by domoritz** [comment]
Everything is esm now!
